import React, { useState, useEffect } from 'react';
import { Loader2, Activity, CheckCircle2, XCircle, AlertCircle, ArrowLeft, Users, ShieldAlert } from 'lucide-react';
import { fetchSuggestedPodsForReview, runMatchingEngine, approveSuggestedPod, rejectSuggestedPod } from '../../../api/matching';

export default function AdminPodReview({ setActiveScreen, adminUser, showToast, showConfirm }) {
  const [proposals, setProposals] = useState([]);
  const [loading, setLoading] = useState(true);
  const [runningEngine, setRunningEngine] = useState(false);
  const [processingAction, setProcessingAction] = useState(false);

  const loadProposals = async () => {
    try {
      setLoading(true);
      const data = await fetchSuggestedPodsForReview();
      setProposals(data);
    } catch (err) {
      console.error('Failed to load proposals:', err);
      showToast(err.message || 'Failed to load suggested pods.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadProposals();
  }, []);

  const handleRunMatchingEngine = async () => {
    setRunningEngine(true);
    try {
      const result = await runMatchingEngine(adminUser?.id);
      if (result.podsCreated > 0) {
        showToast(`Successfully matched ${result.matchedCount} users into ${result.podsCreated} proposed pods!`, 'success');
        await loadProposals();
      } else {
        showToast('Matching run completed: No new compatible groups could be formed with the current weights.');
      }
    } catch (err) {
      console.error('Matching Engine failed:', err);
      showToast(err.message || 'Matching Engine execution failed.');
    } finally {
      setRunningEngine(false);
    }
  };

  const handleApprovePod = async (podId) => {
    setProcessingAction(true);
    try {
      await approveSuggestedPod(podId, adminUser?.id);
      showToast('Matched Pod approved! Suggestion is now visible to matched members.', 'success');
      await loadProposals();
    } catch (err) {
      console.error('Approve failed:', err);
      showToast(err.message || 'Failed to approve matched pod.');
    } finally {
      setProcessingAction(false);
    }
  };

  const handleRejectPod = async (podId) => {
    showConfirm(
      'Reject Match Proposal',
      'Are you sure you want to reject and dissolve this proposed matched pod? Members will be returned to the matching pool.',
      async () => {
        setProcessingAction(true);
        try {
          await rejectSuggestedPod(podId, adminUser?.id);
          showToast('Match proposal dissolved successfully.', 'success');
          await loadProposals();
        } catch (err) {
          console.error('Reject failed:', err);
          showToast(err.message || 'Failed to dissolve match proposal.');
        } finally {
          setProcessingAction(false);
        }
      },
      'danger',
      'Dissolve Proposal'
    );
  };

  return (
    <div className="w-full text-left animate-fade space-y-6">
      {/* Header section */}
      <div className="flex flex-wrap justify-between items-start gap-4">
        <div>
          <div className="font-mono text-[11px] uppercase tracking-wider text-amber mb-1 font-bold">Admin / Moderation</div>
          <h3 className="font-display font-extrabold text-2.5xl text-ink">Suggested Pod Review</h3>
          <p className="text-ink-dim text-sm mt-1">Evaluate and approve compatibility-based groups generated by the Matching Engine.</p>
        </div>
        <button
          onClick={handleRunMatchingEngine}
          disabled={runningEngine || loading}
          className="bg-ink hover:bg-[#2450C4] text-white rounded-xl py-2.5 px-5 text-xs font-bold transition-all shadow flex items-center gap-2 cursor-pointer disabled:opacity-85"
        >
          {runningEngine ? (
            <>
              <Loader2 className="w-3.5 h-3.5 animate-spin" /> Running Engine...
            </>
          ) : (
            <>
              <Activity className="w-3.5 h-3.5" /> Run Matching Engine
            </>
          )}
        </button>
      </div>

      {loading ? (
        <div className="py-16 text-center text-ink-dim font-medium">
          <div className="flex items-center justify-center gap-2">
            <Loader2 className="w-5 h-5 animate-spin text-amber" />
            Loading match proposals...
          </div>
        </div>
      ) : proposals.length === 0 ? (
        <div className="border border-border border-dashed rounded-2xl p-10 bg-panel-alt/25 text-center max-w-[560px] mx-auto my-6 flex flex-col items-center">
          <div className="w-12 h-12 rounded-xl bg-slate-50 text-ink-dim flex items-center justify-center mb-4">
            <Activity className="w-6 h-6" />
          </div>
          <p className="text-ink-dim text-sm font-semibold mb-1">No suggested Pods waiting for approval</p>
          <p className="text-xs text-ink-dim/75 max-w-[360px] leading-relaxed mb-6">
            There are currently no active match proposals. Run the Matching Engine above to evaluate compatible users in the matching pool.
          </p>
          <button
            onClick={() => setActiveScreen('admin-matching')}
            className="bg-transparent border border-border text-ink rounded-lg py-2 px-4 text-xs font-bold hover:bg-panel-alt transition-colors cursor-pointer"
          >
            Configure Weights &amp; Run
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {proposals.map(pod => (
            <div key={pod.id} className="border border-border rounded-2xl p-6 bg-white shadow-sm flex flex-col justify-between hover:shadow-md transition-shadow">
              <div>
                <div className="flex justify-between items-start mb-4">
                  <div>
                    <h4 className="font-display font-extrabold text-lg text-ink leading-tight mb-1">
                      {pod.name}
                    </h4>
                    <span className="bg-[#EAFDF8] text-sage border border-sage/10 text-[10px] font-bold px-2 py-0.5 rounded uppercase tracking-wider w-fit">
                      Proposed Match
                    </span>
                  </div>
                  <div className="w-9 h-9 rounded-lg bg-teal-soft/40 text-teal flex items-center justify-center font-bold text-sm">
                    {Math.round(pod.members.reduce((acc, m) => acc + m.readinessScore, 0) / pod.members.length)}%
                  </div>
                </div>

                <p className="text-ink-dim text-xs leading-relaxed mb-4">
                  {pod.description}
                </p>

                <div className="border-t border-border/60 pt-4 mt-2">
                  <h5 className="text-[10px] font-mono uppercase tracking-wider text-ink-dim font-bold mb-3">Matched Group Candidates ({pod.members.length})</h5>
                  <div className="space-y-3">
                    {pod.members.map(member => (
                      <div key={member.id} className="flex justify-between items-center bg-slate-50 rounded-xl p-2.5 border border-border/40">
                        <div className="flex flex-col text-left">
                          <span className="text-xs font-bold text-ink">{member.name} {member.role === 'CREATOR' && <span className="text-[10px] text-amber font-mono">(Lead)</span>}</span>
                          <span className="text-[10px] text-ink-dim mt-0.5">{member.email}</span>
                        </div>
                        <div className="text-right">
                          <span className="text-[10px] font-mono font-bold text-ink-dim">{member.timeline} timeline</span>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              <div className="flex gap-3 mt-6 pt-4 border-t border-border/60">
                <button
                  onClick={() => handleApprovePod(pod.id)}
                  disabled={processingAction}
                  className="flex-1 bg-ink hover:bg-[#2450C4] text-white rounded-lg py-2 text-xs font-bold transition-colors cursor-pointer text-center disabled:opacity-80"
                >
                  Approve Pod
                </button>
                <button
                  onClick={() => handleRejectPod(pod.id)}
                  disabled={processingAction}
                  className="flex-1 bg-transparent border border-rust text-rust hover:bg-red-50 rounded-lg py-2 text-xs font-bold transition-colors cursor-pointer text-center disabled:opacity-80"
                >
                  Reject Proposal
                </button>
              </div>
            </div>
          ))}
        </div>
      )}

      <button
        onClick={() => setActiveScreen('admin-dashboard')}
        className="bg-transparent border border-border text-ink font-bold text-sm px-5 py-2.5 rounded-xl hover:bg-panel-alt transition-colors cursor-pointer mt-6"
      >
        Back to dashboard
      </button>
    </div>
  );
}
